### ISSUE TITLE
Upper/lower case mismatch - problem in Linux

### ISSUE THREAD

**Issue by BenjaminBlankertz** [FabLabBerlin/visicut-settings#1]
I use visicut in Linux in the FabLab Berlin and had the problem that the settings for the materials were not loaded. I found out that the cause is an upper vs. lower case mismatch. The machine is called 'zing' with lowercase 'z', but the subfolder of 'laserprofiles' in the FabLabBerlin settings is called 'Zing' with uppercase 'Z'. Renaming the folder to 'zing' resolves the problem. Alternatively, renaming the device to 'Zing' would probably also resolve the issue.

**Comment by kr15h** [comment]
Thanks. Will check that.
